### ISSUE TITLE
Object.dirname is deprecated.

### ISSUE THREAD

**Issue by Adri1G** [tvincent056/linter-gcc2#10]
Argument to `path.dirname` must be a string
```
Object.dirname (/usr/share/atom/resources/app.asar/src/electron-shims.js:9:10)
Object.buildCommand (/home/pastore/.atom/packages/linter-gcc2/lib/utility.js:228:36)
Object.lint (/home/pastore/.atom/packages/linter-gcc2/lib/main.js:149:36)
<unknown> (/home/pastore/.atom/packages/linter-gcc2/lib/main.js:215:24)
```

**Comment by 2012VP113** [comment]
Argument to path.dirname must be a string

Object.dirname - C:\Users\Root\AppData\Local\atom\app-1.41.0\resources\app.asar\src\electron-shims.js:9:10
Object.settings - C:\Users\Root\.atom\packages\linter-gcc2\lib\config.js:26:25
Object.buildCommand - C:\Users\Root\.atom\packages\linter-gcc2\lib\utility.js:133:23
Object.lint - C:\Users\Root\.atom\packages\linter-gcc2-master\lib\main.js:149:36
<unknown> - C:\Users\Root\.atom\packages\linter-gcc2-master\lib\main.js:215:24
Argument to path.dirname must be a string

Object.dirname - C:\Users\Root\AppData\Local\atom\app-1.41.0\resources\app.asar\src\electron-shims.js:9:10
Object.buildCommand - C:\Users\Root\.atom\packages\linter-gcc2\lib\utility.js:231:36
Object.lint - C:\Users\Root\.atom\packages\linter-gcc2-master\lib\main.js:149:36
<unknown> - C:\Users\Root\.atom\packages\linter-gcc2-master\lib\main.js:215:24

**Comment by 2012VP113** [comment]
Argument to path.dirname must be a string

Object.dirname - C:\Users\Root\AppData\Local\atom\app-1.41.0\resources\app.asar\src\electron-shims.js:9:10
Object.settings - C:\Users\Root\.atom\packages\linter-gcc2\lib\config.js:26:25
Object.buildCommand - C:\Users\Root\.atom\packages\linter-gcc2\lib\utility.js:133:23
Object.lint - C:\Users\Root\.atom\packages\linter-gcc2-master\lib\main.js:149:36
<unknown> - C:\Users\Root\.atom\packages\linter-gcc2-master\lib\main.js:215:24
Argument to path.dirname must be a string

Object.dirname - C:\Users\Root\AppData\Local\atom\app-1.41.0\resources\app.asar\src\electron-shims.js:9:10
Object.buildCommand - C:\Users\Root\.atom\packages\linter-gcc2\lib\utility.js:231:36
Object.lint - C:\Users\Root\.atom\packages\linter-gcc2-master\lib\main.js:149:36
<unknown> - C:\Users\Root\.atom\packages\linter-gcc2-master\lib\main.js:215:24

**Comment by 2012VP113** [comment]
Argument to path.dirname must be a string

Object.dirname - C:\Users\Root\AppData\Local\atom\app-1.41.0\resources\app.asar\src\electron-shims.js:9:10
Object.settings - C:\Users\Root\.atom\packages\linter-gcc2\lib\config.js:26:25
Object.buildCommand - C:\Users\Root\.atom\packages\linter-gcc2\lib\utility.js:133:23
Object.lint - C:\Users\Root\.atom\packages\linter-gcc2-master\lib\main.js:149:36
<unknown> - C:\Users\Root\.atom\packages\linter-gcc2-master\lib\main.js:215:24
Argument to path.dirname must be a string

Object.dirname - C:\Users\Root\AppData\Local\atom\app-1.41.0\resources\app.asar\src\electron-shims.js:9:10
Object.buildCommand - C:\Users\Root\.atom\packages\linter-gcc2\lib\utility.js:231:36
Object.lint - C:\Users\Root\.atom\packages\linter-gcc2-master\lib\main.js:149:36
<unknown> - C:\Users\Root\.atom\packages\linter-gcc2-master\lib\main.js:215:24

**Comment by 2012VP113** [comment]
Argument to path.dirname must be a string

Object.dirname - C:\Users\Root\AppData\Local\atom\app-1.41.0\resources\app.asar\src\electron-shims.js:9:10
Object.settings - C:\Users\Root\.atom\packages\linter-gcc2\lib\config.js:26:25
Object.buildCommand - C:\Users\Root\.atom\packages\linter-gcc2\lib\utility.js:133:23
Object.lint - C:\Users\Root\.atom\packages\linter-gcc2-master\lib\main.js:149:36
<unknown> - C:\Users\Root\.atom\packages\linter-gcc2-master\lib\main.js:215:24
Argument to path.dirname must be a string

Object.dirname - C:\Users\Root\AppData\Local\atom\app-1.41.0\resources\app.asar\src\electron-shims.js:9:10
Object.buildCommand - C:\Users\Root\.atom\packages\linter-gcc2\lib\utility.js:231:36
Object.lint - C:\Users\Root\.atom\packages\linter-gcc2-master\lib\main.js:149:36
<unknown> - C:\Users\Root\.atom\packages\linter-gcc2-master\lib\main.js:215:24

**Comment by 2012VP113** [comment]
Argument to path.dirname must be a string

Object.dirname - C:\Users\Root\AppData\Local\atom\app-1.41.0\resources\app.asar\src\electron-shims.js:9:10
Object.settings - C:\Users\Root\.atom\packages\linter-gcc2\lib\config.js:26:25
Object.buildCommand - C:\Users\Root\.atom\packages\linter-gcc2\lib\utility.js:133:23
Object.lint - C:\Users\Root\.atom\packages\linter-gcc2-master\lib\main.js:149:36
<unknown> - C:\Users\Root\.atom\packages\linter-gcc2-master\lib\main.js:215:24
Argument to path.dirname must be a string

Object.dirname - C:\Users\Root\AppData\Local\atom\app-1.41.0\resources\app.asar\src\electron-shims.js:9:10
Object.buildCommand - C:\Users\Root\.atom\packages\linter-gcc2\lib\utility.js:231:36
Object.lint - C:\Users\Root\.atom\packages\linter-gcc2-master\lib\main.js:149:36
<unknown> - C:\Users\Root\.atom\packages\linter-gcc2-master\lib\main.js:215:24

**Comment by 2012VP113** [comment]
Argument to path.dirname must be a string

Object.dirname - C:\Users\Root\AppData\Local\atom\app-1.41.0\resources\app.asar\src\electron-shims.js:9:10
Object.settings - C:\Users\Root\.atom\packages\linter-gcc2\lib\config.js:26:25
Object.buildCommand - C:\Users\Root\.atom\packages\linter-gcc2\lib\utility.js:133:23
Object.lint - C:\Users\Root\.atom\packages\linter-gcc2-master\lib\main.js:149:36
<unknown> - C:\Users\Root\.atom\packages\linter-gcc2-master\lib\main.js:215:24
Argument to path.dirname must be a string

Object.dirname - C:\Users\Root\AppData\Local\atom\app-1.41.0\resources\app.asar\src\electron-shims.js:9:10
Object.buildCommand - C:\Users\Root\.atom\packages\linter-gcc2\lib\utility.js:231:36
Object.lint - C:\Users\Root\.atom\packages\linter-gcc2-master\lib\main.js:149:36
<unknown> - C:\Users\Root\.atom\packages\linter-gcc2-master\lib\main.js:215:24
