### ISSUE TITLE
Cannot read property 'start' of undefined

### ISSUE THREAD

**Issue by crswong888** [tvincent056/linter-gcc2#8]
Hello,

I have virtually no coding experience. I am learning all this stuff and that's why this linter is very useful to me.

Thus, I will not try to provide a super-thorough explanation for the issue I am having. All I know is that earlier this week, linter-gcc2 was working fine and now its not. I've tried this on two different computers and got the same error. 

What I've noticed is that when intentionally messing up my code, sometimes the linter will pick up on it, and then Ill fix it but the error won't go away. Other times (most of the time) it won't lint at all. I know there was a new PR on Atom recently, perhaps this messed with this linter? And this isn't specific to whether I use CMake or AutoTools or just a standard Makefile, none of my projects are being linted! I've changed nothing in my settings from when it was working for me on Monday night.

Please look into this issue, this tool is great!

**Comment by crswong888** [comment]
Here is the full error message:

```
Uncaught (in promise) TypeError: Cannot read property 'start' of undefined
    at messageKey (/home/crswong888/.atom/packages/linter/lib/helpers.js:72:69)
    at normalizeMessages (/home/crswong888/.atom/packages/linter/lib/helpers.js:108:19)
    at IndieDelegate.setAllMessages (/home/crswong888/.atom/packages/linter/lib/indie-delegate.js:69:5)
    at /home/crswong888/.atom/packages/linter-gcc2/lib/main.js:177:35
    at <anonymous>
```

**Comment by tvincent056** [comment]
@crswong888 It looks like there may be two problems here. It appears the underlying linter module couldn't find the position property (like line number and column) for the error message. I found that we forgot to add a position property to the default message that gets created when linter-gcc2 fails to properly parse the gcc output message. That is fixed now but you may have another problem since this only occurs when parsing fails. Pull the update (v0.8.6) and let me know if anything changes.

**Comment by crswong888** [comment]
Okay, this update fixed the issues I had before. It is now properly linting on-the-fly and reporting errors when I mess up and unreporting errors when I fix it. Thank you so much!

Here is the new issue: whenever I make any change to my C scripts, the linter-UI reports errors like the one shown in this screenshot:

![screenshot from 2019-02-23 19-43-39](https://user-images.githubusercontent.com/41302548/53293520-5b272600-37a3-11e9-9829-4cb6354190bd.png)

Notice how they always occur in line 1:1.

Now, lets say I mess it up and take away some semi-colons here. Then, these original errors go away and the linter rightfully reports the errors. Check it out:

![screenshot from 2019-02-23 19-46-04](https://user-images.githubusercontent.com/41302548/53293530-ae00dd80-37a3-11e9-8421-c371e7ccca8f.png)

**Comment by tvincent056** [comment]
@crswong888 Those look like linking errors (which linter-gcc2 isn't really meant to handle). You should be able to suppress those by adding "-c" to your compile flags (either in Settings under "C Flags" or in your .gcc-flags.json or compile_commands.json files)

**Comment by crswong888** [comment]
Yes, you are correct. Everything is working as it was now. Thank you Mr. @tvincent056 for this great package!
